---
name: Docker Image CI

on:
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: artis3n/docker-almalinux8-ansible

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: hadolint/hadolint-action@v3.0.0
        with:
          ignore: DL3003,DL3033,DL3059,DL3013,SC2039,SC2086,SC3037

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Install Goss
      uses: e1himself/goss-installation-action@v1.2.1

    - name: Build and Export
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: false
        load: true
        tags: ${{ env.IMAGE_NAME }}:test
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Test the Docker image
      run: dgoss run -it --rm --privileged --cgroupns=host --volume=/sys/fs/cgroup:/sys/fs/cgroup:rw ${{ env.IMAGE_NAME }}:test
